### ISSUE TITLE
The Gateway should be able to upload and persist a Filecoin file

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/gateway#49]
The gateway should expose a method allowing a user to upload the content of a file for further retrieval. 

This functionality should be able to be enabled/disabled by configuration.

**Comment by r-marques** [comment]
We already added support to upload to Filecoin. Support for other methods should be easy to add using the data plugins.

Should this be closed or is there something more that we should do?

**Comment by aaitor** [comment]
For sake of simplicity I think makes sense to keep this one only for the Filecoin support (issue renamed). We can close this one and open others to allow to persist into S3, Azure, etc.
