### ISSUE TITLE
Pull contract information from pypi instead of file system

### ISSUE THREAD

**Issue by H34D** [nevermined-io/gateway#65]
Right now the gateway loads the contract informations (addresses, ABIs) from the file system. It has a reference to the contracts lib and the code is tested against this lib, therefore it should also take the contract information from the contracts lib instead of loading them from the file system somwhere else. 

This lead to a problem on production where the gateway was run with a wrong version of the artifacts. Also it would make the installation less complex (no need for minio then anymore, nothing loaded sideways).

**Comment by r-marques** [comment]
This is now deprecated in favor of the artifacts repo
